#!/usr/bin/env python3
from UserAgent import UserAgent as UA
from Player import Player
from Players.FullyRandomPlayer import FullyRandomPlayer as FRP
from Players.AlwaysCallPlayer import AlwaysCallPlayer as ACP
from CLISpecUserAgent import CLISpecUserAgent as CLIUA
from TexasHoldEmGame import TexasHoldEmGame as Game

game = Game()
player = FRP('Norbert')
game.playersNeeded = [player]
game.addPlayer(player)
game.addPlayer(FRP('Brigitte'))
game.addPlayer(FRP('Alex'))
game.addPlayer(FRP('Jill'))
game.addPlayer(FRP('P'))
# game.addPlayer(Player('Daniel'))
# game.addPlayer(Player('Kaori'))
# game.addPlayer(Player('Miguel'))
# game.addPlayer(Player('Warren'))
# game.addPlayer(Player('Stefanie'))

game.addSpectator(CLIUA('Jim'))

wins = game.runGame()

for pl, win in wins.items():
    print(pl.name+' wins '+str(win))
