#!/usr/bin/env python3
from UserAgent import UserAgent as UA
from Player import Player
from Players.FullyRandomPlayer import FullyRandomPlayer as FRP
from Players.CLIPlayer import CLIPlayer as CLIP
from Players.AlwaysCallPlayer import AlwaysCallPlayer as ACP
from CLISpecUserAgent import CLISpecUserAgent as CLIUA
from TexasHoldEmGame import TexasHoldEmGame as Game
from Players.SimpleAIPlayer import SimpleAIPlayer as AIP

inp = None
while inp is None:
    print()
    inp = input('enter your name: ')
    if len(inp) > 10 or len(inp) < 2:
        print('not more than 10 or less than 2 characters, please')
        inp = None

game = Game()
player = CLIP(inp)
game.playersNeeded = [player]
game.addPlayer(player)
game.addPlayer(AIP('Brigitte'))
game.addPlayer(AIP('Alex'))
game.addPlayer(AIP('Jill'))
game.addPlayer(AIP('P'))
game.addPlayer(AIP('Kaori'))
game.addPlayer(AIP('Miguel'))

wins = game.runGame()

for pl, win in wins.items():
    print(pl.name+' wins '+str(win))
